L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/libc_backends/lib/misc
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/libc_backends
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/misc/Makefile
include $(L4DIR)/mk/lib.mk
