L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/io/io/server/src/drivers/pci
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/io/io
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers/pci/Makefile
include $(L4DIR)/mk/lib.mk
