L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/lua/examples/interpr
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/lua
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/lua/examples/interpr/Makefile
include $(L4DIR)/mk/prog.mk
