/*
 *
 * Automatically generated file; DO NOT EDIT.
 * Fiasco configuration
 *
 */
#define CONFIG_PERF_CNT 1
#define CONFIG_BIT32 1
#define CONFIG_REGPARM3 1
#define CONFIG_SCHED_APIC 1
#define CONFIG_ABI "vf"
#define CONFIG_CXX "g++"
#define CONFIG_LABEL ""
#define CONFIG_HAS_CPU_VIRT 1
#define CONFIG_HAS_JDB_DISASM_OPTION 1
#define CONFIG_JDB 1
#define CONFIG_WARN_WARNING 1
#define CONFIG_JDB_GZIP 1
#define CONFIG_PF_PC 1
#define CONFIG_SCHED_FIXED_PRIO 1
#define CONFIG_HAS_VIRT_OBJ_SPACE_OPTION 1
#define CONFIG_CONTEXT_4K 1
#define CONFIG_HOST_CC "gcc"
#define CONFIG_ABI_VF 1
#define CONFIG_NO_FRAME_PTR 1
#define CONFIG_NO_LDT 1
#define CONFIG_WATCHDOG 1
#define CONFIG_NO_IO_PAGEFAULT 1
#define CONFIG_INLINE 1
#define CONFIG_SERIAL 1
#define CONFIG_POWERSAVE_GETCHAR 1
#define CONFIG_JDB_DISASM 1
#define CONFIG_IA32 1
#define CONFIG_HAS_IOMMU_OPTION 1
#define CONFIG_XARCH "ia32"
#define CONFIG_CC "gcc"
#define CONFIG_HOST_CXX "g++"
#define CONFIG_JDB_LOGGING 1
#define CONFIG_WARN_LEVEL 1
#define CONFIG_HAS_JDB_GZIP_OPTION 1
#define CONFIG_HAS_MP_OPTION 1
#define CONFIG_VIRT_OBJ_SPACE 1
#define CONFIG_HAS_WATCHDOG_OPTION 1
#define CONFIG_HAS_SERIAL_OPTION 1
