# This Makefile is a template for the Makefile used in the build
# directories.
#

srcdir  := /media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src
objbase := $(shell pwd)

include $(srcdir)/Makefile

