#define OFS__THREAD__STATE 0x4
#define OFS__THREAD__KERNEL_SP 0x20
#define OFS__THREAD__DONATEE 0x38
#define OFS__THREAD__LOCK_CNT 0x40
#define OFS__THREAD__SCHED_CONTEXT 0x44
#define OFS__THREAD__SCHED 0x60
#define OFS__THREAD__FPU_STATE 0x64
#define OFS__THREAD__CONSUMED_TIME 0x68
#define OFS__THREAD__REPLY_CAP 0xec
#define OFS__THREAD__PARTNER 0xe4
#define OFS__THREAD__RCV_REGS 0xe8
#define OFS__THREAD__TIMEOUT 0xa4
#define OFS__THREAD__SPACE 0x30
#define OFS__THREAD__PAGER 0x144
#define OFS__THREAD__RECOVER_JMPBUF 0x9c
#define OFS__THREAD__MAGIC 0x154
#define OFS__THREAD__MAX 0x160
#define OFS__THREAD__USER_VCPU 0xd8
#define OFS__THREAD__KERN_VCPU 0xdc
#define OFS__THREAD__VCPU_STATE 0xdc
#define OFS__SCHED_CONTEXT__MAX 0x1c
#define OFS__MEM_SPACE__PGTABLE 0x8
#define OFS__TBUF_STATUS__KERNCNTS 0x70
#define CAST__Thread_TO_Receiver 0x0
#define CAST__Thread_TO_Sender 0xfc
#define VAL__SIZEOF_TRAP_STATE 0x4c
#define OFS__TRAP_STATE__IP 0x38
#define OFS__VCPU_STATE__TREX 0x20
#define OFS__VCPU_STATE__ENTRY_IP 0x98
#define OFS__VCPU_STATE__ENTRY_SP 0x9c
#define VAL__Thread_ready 0x1
#define VAL__Thread_cancel 0x80
#define VAL__Thread_dis_alien 0x20000
#define VAL__Thread_ipc_mask 0x1c
#define VAL__Thread_ext_vcpu_enabled 0x2000000
#define VAL__Thread_fpu_owner 0x8000
#define VAL__Thread_alien_or_vcpu_user 0x810000
#define VAL__Thread_vcpu_state_mask 0x3c00000
#define VAL__MEM_LAYOUT__PHYSMEM 0xfc400000
#define VAL__MEM_LAYOUT__TBUF_STATUS_PAGE 0xeac06000
#define VAL__MEM_LAYOUT__LAPIC 0xeac00000
#define VAL__MEM_LAYOUT__IO_BITMAP 0xefc00000
#define VAL__MEM_LAYOUT__SYSCALLS 0xeacff000
#define OFS__CPU__TSS 0xe0
