L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/bootstrap/server/src
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/bootstrap
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src/Makeconf.local
OSYSTEM=x86
SYSTEM=x86_gen
ARCH=x86
CPU=gen
L4API=
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src/Make.rules
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/bootstrap/server/src/Make.rules
include $(L4DIR)/mk/prog.mk
