// AUTOMATICALLY GENERATED -- DO NOT EDIT!         -*- c++ -*-

#ifndef kernel_thread_i_h
#define kernel_thread_i_h
#line 28 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread.cpp"

#include <cstdlib>
#line 30 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread.cpp"
#include <cstdio>
#line 31 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread.cpp"

#include "config.h"
#line 33 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread.cpp"
#include "cpu.h"
#line 34 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread.cpp"
#include "delayloop.h"
#line 35 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread.cpp"
#include "globals.h"
#line 36 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread.cpp"
#include "helping_lock.h"
#line 37 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread.cpp"
#include "kernel_task.h"
#line 38 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread.cpp"
#include "per_cpu_data_alloc.h"
#line 40 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread.cpp"
#include "task.h"
#line 41 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread.cpp"
#include "thread.h"
#line 42 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread.cpp"
#include "thread_state.h"
#line 43 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread.cpp"
#include "timer.h"
#line 44 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread.cpp"
#include "timer_tick.h"
#line 45 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread.cpp"
#include "watchdog.h"
#line 2 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread-std.cpp"

#include "assert_opt.h"
#line 4 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread-std.cpp"
#include "config.h"
#line 5 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread-std.cpp"
#include "factory.h"
#line 6 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread-std.cpp"
#include "initcalls.h"
#line 7 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread-std.cpp"
#include "ipc_gate.h"
#line 8 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread-std.cpp"
#include "irq.h"
#line 9 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread-std.cpp"
#include "koptions.h"
#line 10 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread-std.cpp"
#include "map_util.h"
#line 11 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread-std.cpp"
#include "mem_layout.h"
#line 12 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread-std.cpp"
#include "sigma0_task.h"
#line 13 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread-std.cpp"
#include "task.h"
#line 14 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread-std.cpp"
#include "thread_object.h"
#line 15 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread-std.cpp"
#include "types.h"
#line 16 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/kernel_thread-std.cpp"
#include "ram_quota.h"
#line 3 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/kernel_thread-ia32.cpp"

#include "apic.h"
#line 5 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/kernel_thread-ia32.cpp"
#include "config.h"
#line 6 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/kernel_thread-ia32.cpp"
#include "cpu.h"
#line 7 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/kernel_thread-ia32.cpp"
#include "io_apic.h"
#line 8 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/kernel_thread-ia32.cpp"
#include "irq_mgr.h"
#line 9 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/kernel_thread-ia32.cpp"
#include "koptions.h"
#line 11 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/kernel_thread-ia32.cpp"
#include "pic.h"
#line 12 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/kernel_thread-ia32.cpp"
#include "trap_state.h"
#line 13 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/kernel_thread-ia32.cpp"
#include "watchdog.h"

#endif // kernel_thread_i_h
