// AUTOMATICALLY GENERATED -- DO NOT EDIT!         -*- c++ -*-

#ifndef startup_i_h
#define startup_i_h
#line 16 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/startup.cpp"

#include "static_init.h"
#line 2 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"

#include <cstdlib>
#line 4 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include <cstdio>
#line 5 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"

#include "apic.h"
#line 7 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "banner.h"
#line 8 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "boot_console.h"
#line 9 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "boot_info.h"
#line 10 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "config.h"
#line 11 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "cpu.h"
#line 12 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "fpu.h"
#line 13 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "idt.h"
#line 14 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "initcalls.h"
#line 15 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "io_apic.h"
#line 16 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "ipi.h"
#line 17 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "irq_chip_pic.h"
#line 18 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "irq_mgr.h"
#line 19 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "kernel_console.h"
#line 20 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "kernel_task.h"
#line 21 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "kip_init.h"
#line 22 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "kernel_uart.h"
#line 23 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "kmem.h"
#line 24 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "kmem_alloc.h"
#line 25 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "per_cpu_data.h"
#line 26 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "per_cpu_data_alloc.h"
#line 27 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "pic.h"
#line 28 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "platform_control.h"
#line 29 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "static_init.h"
#line 30 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "std_macros.h"
#line 31 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "thread.h"
#line 32 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "timer.h"
#line 33 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "utcb_init.h"
#line 34 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"

#include "io_apic.h"
#line 36 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "io_apic_remapped.h"
#line 37 "/media/fedora_work/project/real-time/l4re/src/kernel/fiasco/src/kern/ia32/startup-ia32.cpp"
#include "intel_iommu.h"

#endif // startup_i_h
