# automatically created -- modifications will be lost
SRC := /media/fedora_work/project/real-time/l4re/src/l4/pkg/io/io/server/src/drivers
OBJ := /media/fedora_work/project/real-time/l4re/src/l4/mybuild
.PHONY: $(MAKECMDGOALS) do-all-make-goals
do-all-make-goals:
	@PWD=$(SRC) $(MAKE) -C $(SRC) O=$(OBJ) $(MAKECMDGOALS)
$(MAKECMDGOALS): do-all-make-goals
