L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/l4re/util/libs
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/l4re
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re/util/libs/Makefile
include $(L4DIR)/mk/lib.mk
