L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/l4re_c/util/lib
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/l4re_c
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/l4re_c/util/lib/Makefile
include $(L4DIR)/mk/lib.mk
