L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/x86emu/lib/int10
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/x86emu
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/x86emu/lib/int10/Makefile
include $(L4DIR)/mk/lib.mk
