L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/ldso/libdl
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/ldso
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldso/libdl/Makefile
include $(L4DIR)/mk/lib.mk
