L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/libc_backends/lib/minimal_io
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/libc_backends
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libc_backends/lib/minimal_io/Makefile
include $(L4DIR)/mk/lib.mk
