L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/shmc/lib/ringbuf
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/shmc
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/shmc/lib/ringbuf/Makefile
include $(L4DIR)/mk/lib.mk
