L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/cxx/lib/be/kdebug
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/cxx
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/cxx/lib/be/kdebug/Makefile
include $(L4DIR)/mk/lib.mk
