L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/libstdc++-v3-minimal
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/libstdc++-v3-minimal
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/libstdc++-v3-minimal/Makefile
include $(L4DIR)/mk/lib.mk
