L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/rtc/lib/client
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/rtc
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/rtc/lib/client/Makefile
include $(L4DIR)/mk/lib.mk
