L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/uclibc/lib/uclibc
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/uclibc
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc/Make.rules
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/uclibc/Make.rules
include $(L4DIR)/mk/lib.mk
