L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/ldscripts
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/ldscripts
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts/Makeconf.local
OSYSTEM=x86
SYSTEM=x86_gen
ARCH=x86
CPU=gen
L4API=
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/ldscripts/Makefile
include $(L4DIR)/mk/lib.mk
