L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/uclibc-minimal/libc
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/uclibc-minimal
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc/Makeconf.local
OSYSTEM=x86
SYSTEM=x86_gen
ARCH=x86
CPU=gen
L4API=
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc/Make.rules
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc-minimal/libc/Make.rules
include $(L4DIR)/mk/lib.mk
