L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/lxfuxlibc/lib/libc_be
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/lxfuxlibc
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/lxfuxlibc/lib/libc_be/Makefile
include $(L4DIR)/mk/lib.mk
