L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/input/lib/src-dummy
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/input
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/input
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/input
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/input/lib/src-dummy/Makefile
include $(L4DIR)/mk/lib.mk
