L4DIR=/media/fedora_work/project/real-time/l4re/src/l4
OBJ_BASE=/media/fedora_work/project/real-time/l4re/src/l4/mybuild
OBJ_DIR=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/uclibc/lib/minimal_l4re
SRC_DIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
PKGDIR=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc
PKGDIR_ABS=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc
PKGDIR_OBJ=/media/fedora_work/project/real-time/l4re/src/l4/mybuild/pkg/l4re-core/uclibc
MAKECONFLOCAL=/media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re/Makeconf.local
OSYSTEM=x86-l4f
SYSTEM=x86_gen-l4f
ARCH=x86
CPU=gen
L4API=l4f
vpath %.c /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.cc /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.cpp /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.f /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.F /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.f90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.F90 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.f95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.F95 /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.S /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.y /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.l /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.ld /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.dpe /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
vpath %.dts /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re
.general.d: /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re/Makefile
include /media/fedora_work/project/real-time/l4re/src/l4/pkg/l4re-core/uclibc/lib/minimal_l4re/Makefile
include $(L4DIR)/mk/lib.mk
